server:
  port: 8080
  servlet:
    context-path: /escola

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://vavxawfrrtuhjn:2b7c844b8629441c4980491f5c30b5a0c045002adba47c2e5c72f697e6d4e626@ec2-35-171-250-21.compute-1.amazonaws.com:5432/d1cuflagj2obm2
    username: vavxawfrrtuhjn
    password: 2b7c844b8629441c4980491f5c30b5a0c045002adba47c2e5c72f697e6d4e626
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
application:
  description: Projeto Backend - Escola